[helpers]

[default]
depends = ["claude", "cursor"]

[default.variables]

[settings]
default_target_type = "automatic"

[claude.files]
"claude/agents" = { target = "~/.claude/agents", type = "symbolic", recurse = false }
"claude/skills" = { target = "~/.claude/skills", type = "symbolic", recurse = false }

[cursor.files]
"cursor/agents" = { target = "~/.cursor/agents", type = "symbolic", recurse = false }
"cursor/skills" = { target = "~/.cursor/skills", type = "symbolic", recurse = false }
